export const GET_CATEGORIES_TRY = 'GET_CATEGORIES_TRY';
export const GET_CATEGORIES_GO = 'GET_CATEGORIES_GO';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const GET_ACATEGORY_TRY = 'GET_ACATEGORY_TRY';
export const GET_ACATEGORY_GO = 'GET_ACATEGORY_GO';
export const GET_ACATEGORY_FAILED = 'GET_ACATEGORY_FAILED';

export const ADD_CATEGORY_TRY = 'ADD_CATEGORY_TRY';
export const ADD_CATEGORY_GO = 'ADD_CATEGORY_GO';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const EDIT_CATEGORY_TRY = 'EDIT_CATEGORY_TRY';
export const EDIT_CATEGORY_GO = 'EDIT_CATEGORY_GO';
export const EDIT_CATEGORY_FAILED = 'EDIT_CATEGORY_FAILED';

export const REMOVE_CATEGORY_TRY = 'REMOVE_CATEGORY_TRY';
export const REMOVE_CATEGORY_GO = 'REMOVE_CATEGORY_GO';
export const REMOVE_CATEGORY_FAILED = 'REMOVE_CATEGORY_FAILED';

export const FILTER_ITEMS = 'FILTER_ITEMS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const CLEAR_CURRENT = 'CLEAR_CURRENT';
