export const GET_NOTICIAS_TRY = 'GET_NOTICIAS_TRY';
export const GET_NOTICIAS_GO = 'GET_NOTICIAS_GO';
export const GET_NOTICIAS_FAILED = 'GET_NOTICIAS_FAILED';

export const GET_ANOTICIA_TRY = 'GET_ANOTICIA_TRY';
export const GET_ANOTICIA_GO = 'GET_ANOTICIA_GO';
export const GET_ANOTICIA_FAILED = 'GET_ANOTICIA_FAILED';

export const ADD_NOTICIA_TRY = 'ADD_NOTICIA_TRY';
export const ADD_NOTICIA_GO = 'ADD_NOTICIA_GO';
export const ADD_NOTICIA_FAILED = 'ADD_NOTICIA_FAILED';

export const EDIT_NOTICIA_TRY = 'EDIT_NOTICIA_TRY';
export const EDIT_NOTICIA_GO = 'EDIT_NOTICIA_GO';
export const EDIT_NOTICIA_FAILED = 'EDIT_NOTICIA_FAILED';

export const REMOVE_NOTICIA_TRY = 'REMOVE_NOTICIA_TRY';
export const REMOVE_NOTICIA_GO = 'REMOVE_NOTICIA_GO';
export const REMOVE_NOTICIA_FAILED = 'REMOVE_NOTICIA_FAILED';

export const CLEAR_CURRENT = 'CLEAR_CURRENT';
