export const GET_PRODUCTS_TRY = 'GET_PRODUCTS_TRY';
export const GET_PRODUCTS_GO = 'GET_PRODUCTS_GO';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_APRODUCT_TRY = 'GET_APRODUCT_TRY';
export const GET_APRODUCT_GO = 'GET_APRODUCT_GO';
export const GET_APRODUCT_FAILED = 'GET_APRODUCT_FAILED';

export const GET_PREVPROD_TRY = 'GET_PREVPROD_TRY';
export const GET_PREVPROD_GO = 'GET_PREVPROD_GO';
export const GET_PREVPROD_FAILED = 'GET_PREVPROD_FAILED';

export const ADD_PRODUCT_TRY = 'ADD_PRODUCT_TRY';
export const ADD_PRODUCT_GO = 'ADD_PRODUCT_GO';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const EDIT_PRODUCT_TRY = 'EDIT_PRODUCT_TRY';
export const EDIT_PRODUCT_GO = 'EDIT_PRODUCT_GO';
export const EDIT_PRODUCT_FAILED = 'EDIT_PRODUCT_FAILED';

export const REMOVE_PRODUCT_TRY = 'REMOVE_PRODUCT_TRY';
export const REMOVE_PRODUCT_GO = 'REMOVE_PRODUCT_GO';
export const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';

export const CLEAR_CURRENT = 'CLEAR_CURRENT';
