export const GET_FOLDERS_TRY = 'GET_FOLDERS_TRY';
export const GET_FOLDERS_GO = 'GET_FOLDERS_GO';
export const GET_FOLDERS_FAILED = 'GET_FOLDERS_FAILED';

export const GET_AFOLDER_TRY = 'GET_AFOLDER_TRY';
export const GET_AFOLDER_GO = 'GET_AFOLDER_GO';
export const GET_AFOLDER_FAILED = 'GET_AFOLDER_FAILED';

export const ADD_FOLDER_TRY = 'ADD_FOLDER_TRY';
export const ADD_FOLDER_GO = 'ADD_FOLDER_GO';
export const ADD_FOLDER_FAILED = 'ADD_FOLDER_FAILED';

export const EDIT_FOLDER_TRY = 'EDIT_FOLDER_TRY';
export const EDIT_FOLDER_GO = 'EDIT_FOLDER_GO';
export const EDIT_FOLDER_FAILED = 'EDIT_FOLDER_FAILED';

export const REMOVE_FOLDER_TRY = 'REMOVE_FOLDER_TRY';
export const REMOVE_FOLDER_GO = 'REMOVE_FOLDER_GO';
export const REMOVE_FOLDER_FAILED = 'REMOVE_FOLDER_FAILED';

export const FILTER_ITEMS = 'FILTER_ITEMS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const CLEAR_CURRENT = 'CLEAR_CURRENT';
